name: CI
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run (component tests)
        uses: cypress-io/github-action@v5
        with:
          component: true
    
      - name: Cypress run (e2e tests)
        uses: cypress-io/github-action@v5
        with:
          install: false
          start: npm start
          wait-on: 'http://localhost:3000'
